#!/usr/bin/env python3
"""Detect coverage gaps in the Macawiki corpus by cross-referencing controlled vocabularies against actual page metadata."""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from typing import Any

try:
    from .common import ROOT, discover_pages, load_data
except ImportError:
    from common import ROOT, discover_pages, load_data


def compute_coverage() -> dict[str, Any]:
    pages = discover_pages()
    tags_yaml = load_data(ROOT / "data" / "tags.yaml")
    version_claims = load_data(ROOT / "data" / "version-claims.yaml")

    # Collect all values from page metadata
    used_components: set[str] = set()
    used_tags: set[str] = set()
    used_hardware: set[str] = set()
    used_types: set[str] = set()
    page_count_by_component: dict[str, int] = defaultdict(int)
    page_count_by_tag: dict[str, int] = defaultdict(int)
    page_count_by_hardware: dict[str, int] = defaultdict(int)

    for p in pages:
        ptype = str(p.metadata.get("type", ""))
        used_types.add(ptype)

        for comp in (p.metadata.get("components") or []):
            used_components.add(str(comp))
            page_count_by_component[str(comp)] += 1

        for tag in (p.metadata.get("tags") or []):
            used_tags.add(str(tag))
            page_count_by_tag[str(tag)] += 1

        for hw in (p.metadata.get("hardware") or []):
            used_hardware.add(str(hw))
            page_count_by_hardware[str(hw)] += 1

    # Find gaps
    known_components = set(tags_yaml.get("components", []))
    known_tags = set(tags_yaml.get("topic_tags", []))
    known_hardware = set(tags_yaml.get("hardware", []))

    uncovered_components = sorted(known_components - used_components)
    uncovered_tags = sorted(known_tags - used_tags)
    uncovered_hardware = sorted(known_hardware - used_hardware)

    # Version-claim coverage
    vc_list = version_claims.get("claims", []) if isinstance(version_claims, dict) else version_claims
    total_claims = len(vc_list)
    unspecified_claims = sum(
        1 for vc in vc_list if "unspecified" in (vc.get("versions") or [])
    )

    return {
        "total_pages": len(pages),
        "coverage": {
            "components": {
                "total_known": len(known_components),
                "covered": len(used_components),
                "uncovered": uncovered_components,
                "by_page": dict(page_count_by_component),
            },
            "tags": {
                "total_known": len(known_tags),
                "covered": len(used_tags),
                "uncovered": uncovered_tags,
                "by_page": dict(page_count_by_tag),
            },
            "hardware": {
                "total_known": len(known_hardware),
                "covered": len(used_hardware),
                "uncovered": uncovered_hardware,
                "by_page": dict(page_count_by_hardware),
            },
            "page_types": sorted(used_types),
        },
        "version_claims": {
            "total": total_claims,
            "unspecified": unspecified_claims,
            "specified": total_claims - unspecified_claims,
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", action="store_true", help="Output as JSON")
    parser.add_argument("--markdown", type=str, help="Write markdown report to file")
    args = parser.parse_args()

    report = compute_coverage()

    if args.json:
        print(json.dumps(report, ensure_ascii=False, indent=2))
    else:
        print("=== Corpus Coverage Report ===")
        print(f"Total pages: {report['total_pages']}")
        print()

        cov = report["coverage"]
        print(f"Components: {cov['components']['covered']}/{cov['components']['total_known']} covered")
        if cov["components"]["uncovered"]:
            print(f"  Uncovered: {', '.join(cov['components']['uncovered'])}")

        print(f"Tags: {cov['tags']['covered']}/{cov['tags']['total_known']} covered")
        if cov["tags"]["uncovered"]:
            print(f"  Uncovered: {', '.join(cov['tags']['uncovered'])}")

        print(f"Hardware: {cov['hardware']['covered']}/{cov['hardware']['total_known']} covered")
        if cov["hardware"]["uncovered"]:
            print(f"  Uncovered: {', '.join(cov['hardware']['uncovered'])}")

        vc = report["version_claims"]
        print(f"\nVersion claims: {vc['total']} total, {vc['unspecified']} unspecified")

    if args.markdown:
        md_path = ROOT / args.markdown
        md_path.parent.mkdir(parents=True, exist_ok=True)
        lines = [
            "# Corpus Coverage Report",
            "",
            f"Generated by `scripts/coverage_report.py`.",
            f"Total pages: {report['total_pages']}",
            "",
            "## Components",
            f"- Covered: {cov['components']['covered']}/{cov['components']['total_known']}",
        ]
        if cov["components"]["uncovered"]:
            lines.append(f"- Uncovered: {', '.join(cov['components']['uncovered'])}")
        lines += [
            "",
            "## Tags",
            f"- Covered: {cov['tags']['covered']}/{cov['tags']['total_known']}",
        ]
        if cov["tags"]["uncovered"]:
            lines.append(f"- Uncovered: {', '.join(cov['tags']['uncovered'])}")
        lines += [
            "",
            "## Hardware",
            f"- Covered: {cov['hardware']['covered']}/{cov['hardware']['total_known']}",
        ]
        if cov["hardware"]["uncovered"]:
            lines.append(f"- Uncovered: {', '.join(cov['hardware']['uncovered'])}")
        lines += [
            "",
            "## Version Claims",
            f"- {vc['total']} total, {vc['specified']} specified, {vc['unspecified']} unspecified",
        ]
        md_path.write_text("\n".join(lines), encoding="utf-8")
        print(f"\nWrote {md_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
