#!/usr/bin/env python3
"""Generate deterministic Markdown indices and pickle search index from Macawiki frontmatter."""

from __future__ import annotations

import argparse
import pickle
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

try:
    from .common import ROOT, Page, discover_pages, searchable_text
except ImportError:
    from common import ROOT, Page, discover_pages, searchable_text


GENERATED_NOTICE = "<!-- Generated by scripts/generate_indices.py; do not edit manually. -->\n"


def _line(page: Page) -> str:
    metadata = page.metadata
    return f"- [`{metadata['id']}`](../{page.relative_path}) — {metadata['title']}"


def _group(pages: list[Page], field: str) -> dict[str, list[Page]]:
    groups: dict[str, list[Page]] = defaultdict(list)
    for page in pages:
        value = page.metadata.get(field, [])
        values = value if isinstance(value, list) else [value]
        for item in values:
            if item is not None:
                groups[str(item)].append(page)
    return groups


def _render(title: str, groups: dict[str, list[Page]]) -> str:
    lines = [GENERATED_NOTICE.rstrip(), f"# {title}", ""]
    for name in sorted(groups, key=str.casefold):
        lines.extend([f"## {name}", ""])
        for page in sorted(groups[name], key=lambda item: item.metadata["id"]):
            lines.append(_line(page))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def build_pickle_index(pages: list[Page]) -> dict[str, Any]:
    """Build a pre-computed search index for fast lookups.

    Stores pre-computed searchable text and field indices so that query.py
    can filter by field first, then do substring matching on cached text.
    """
    page_data: dict[str, dict[str, Any]] = {}
    by_field: dict[str, dict[str, set[str]]] = defaultdict(lambda: defaultdict(set))

    for page in pages:
        pid = str(page.metadata.get("id", ""))
        page_data[pid] = {
            "id": pid,
            "title": page.metadata.get("title", ""),
            "type": page.metadata.get("type", ""),
            "path": str(page.relative_path),
            "summary": page.metadata.get("summary", ""),
            "confidence": page.metadata.get("confidence"),
            "hardware": page.metadata.get("hardware", []),
            "mxmaca_versions": page.metadata.get("mxmaca_versions", []),
            "sources": page.metadata.get("sources", []),
            "_text": searchable_text(page),
            "_title": str(page.metadata.get("title", "")).casefold(),
            "_id": pid.casefold(),
        }

        # Build by-field indices for fast filtering
        for field in ("type", "components", "hardware", "mxmaca_versions", "tags"):
            values = page.metadata.get(field, [])
            if not isinstance(values, list):
                values = [values] if values else []
            for val in values:
                if val:
                    by_field[field][str(val)].add(pid)

    return {
        "pages": page_data,
        "by_field": {field: {val: sorted(ids) for val, ids in vals.items()} for field, vals in by_field.items()},
    }


def build_indices(pages: list[Page]) -> dict[str, str]:
    return {
        "by-type.md": _render("按页面类型", _group(pages, "type")),
        "by-component.md": _render("按组件", _group(pages, "components")),
        "by-hardware.md": _render("按硬件", _group(pages, "hardware")),
        "by-version.md": _render("按 MXMACA 版本", _group(pages, "mxmaca_versions")),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files are missing or stale")
    args = parser.parse_args()
    pages = discover_pages()
    output_dir = ROOT / "queries"

    # Generate Markdown indices
    generated = build_indices(pages)
    stale: list[str] = []
    for name, content in generated.items():
        path = output_dir / name
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(name)
        else:
            output_dir.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")

    # Generate pickle search index
    pickle_path = output_dir / "index.pickle"
    if args.check:
        if not pickle_path.exists():
            stale.append("index.pickle")
    else:
        index_data = build_pickle_index(pages)
        with open(pickle_path, "wb") as f:
            pickle.dump(index_data, f, protocol=pickle.HIGHEST_PROTOCOL)
        print(f"wrote {pickle_path.relative_to(ROOT)} ({len(index_data['pages'])} pages)")

    if stale:
        print(f"Generated indices are stale: {', '.join(stale)}", file=sys.stderr)
        return 1
    if args.check:
        print(f"Checked {len(generated)} generated indices + pickle index.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
