#!/usr/bin/env python3
"""Generate deterministic Markdown indices from Macawiki frontmatter."""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path

from common import ROOT, Page, discover_pages


GENERATED_NOTICE = "<!-- Generated by scripts/generate_indices.py; do not edit manually. -->\n"


def _line(page: Page) -> str:
    metadata = page.metadata
    return f"- [`{metadata['id']}`](../{page.relative_path}) — {metadata['title']}"


def _group(pages: list[Page], field: str) -> dict[str, list[Page]]:
    groups: dict[str, list[Page]] = defaultdict(list)
    for page in pages:
        value = page.metadata.get(field, [])
        values = value if isinstance(value, list) else [value]
        for item in values:
            if item is not None:
                groups[str(item)].append(page)
    return groups


def _render(title: str, groups: dict[str, list[Page]]) -> str:
    lines = [GENERATED_NOTICE.rstrip(), f"# {title}", ""]
    for name in sorted(groups, key=str.casefold):
        lines.extend([f"## {name}", ""])
        for page in sorted(groups[name], key=lambda item: item.metadata["id"]):
            lines.append(_line(page))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def build_indices(pages: list[Page]) -> dict[str, str]:
    return {
        "by-type.md": _render("按页面类型", _group(pages, "type")),
        "by-component.md": _render("按组件", _group(pages, "components")),
        "by-hardware.md": _render("按硬件", _group(pages, "hardware")),
        "by-version.md": _render("按 MXMACA 版本", _group(pages, "mxmaca_versions")),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files are missing or stale")
    args = parser.parse_args()
    output_dir = ROOT / "queries"
    generated = build_indices(discover_pages())
    stale: list[str] = []
    for name, content in generated.items():
        path = output_dir / name
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(name)
        else:
            output_dir.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        print(f"Generated indices are stale: {', '.join(stale)}", file=sys.stderr)
        return 1
    if args.check:
        print(f"Checked {len(generated)} generated indices.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
